server:
  port: 8091
 
spring:
  application:
    name: crops-microservice
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: cropservice
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:8761/eureka/