name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:

env:
  AWS_REGION: us-east-1 
  S3BUCKET: glp-s3-1 
  S3bucket_CodeGuru: codeguru-reviewer-glp-s3-1 

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set Execute Permissions
        run: chmod -R +x ./.github

      - name: Build and Package Maven for CropService
        working-directory: ${{ github.workspace }}/CropService  # Ensure this path is correct
        run: mvn clean package

      - name: Verify the Target Directory Exists
        run: |
          if [ -d "${{ github.workspace }}/CropService/target" ]; then
            echo "Target directory exists."
          else
            echo "Target directory does not exist."
            exit 1
          fi

      - name: List Contents of Target Directory
        run: ls -al ${{ github.workspace }}/CropService/target

      - name: Upload Artifact to S3
        working-directory: ${{ github.workspace }}/CropService/target
        run: |
          if ls *.war 1> /dev/null 2>&1; then
            aws s3 cp *.war s3://${{ env.S3BUCKET }}/
          else
            echo "No .war files found in the target directory."
            exit 1
          fi

      - name: Upload Artifacts for CodeScan
        uses: actions/upload-artifact@v2
        with:
          name: build-file
          path: ${{ github.workspace }}/CropService/target/*.war
